### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by nikohosn** [Web3Auth/web3auth-unity-sdk#3]
Is this SDK able to be used in a Unity3D WebGL build?

**Comment by hugtor** [comment]
Hi there, for WebGL builds, it is highly recommended to use the web
sdk at GitHub
- Web3Auth/Web3Auth: Simple infrastructure that enables Web3 wallets and
applications to provide seamless user logins for both mainstream and Web3.0
users. <https://github.com/Web3Auth/Web3Auth> then pass whatever you need
(eg. the tokens or etc) to Unity, instead of using the unity sdk directly.

An example of how this can be done is found here - GitHub -
Web3Auth/web3auth-unity-sdk at webgl
<https://github.com/Web3Auth/web3auth-unity-sdk/tree/webgl>
